version: "3"

services:
  # App php-fpm service
  app:
    build:
      context: ./docker/php
      args:
        APP_ENV: ${APP_ENV}
        PHP_VERSION: ${PHP_VERSION}
        REMOTE_WORKING_DIR: ${REMOTE_WORKING_DIR}
    container_name: reactphp-app
    restart: unless-stopped
    volumes:
      - ${LOCAL_WORKING_DIR}:${REMOTE_WORKING_DIR}
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    env_file: .env
    ports:
      - 9001:9001
      - 6001:6001
    networks:
      - reactphp

  nginx:
    image: nginx:alpine
    container_name: reactphp-nginx
    restart: unless-stopped
    volumes:
      - ${LOCAL_WORKING_DIR}:${REMOTE_WORKING_DIR}
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/nginx/ssl/
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    depends_on:
      - app
    networks:
      - reactphp

  database:
    image: mysql:5.7
    container_name: reactphp-database
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USR}
      MYSQL_PASSWORD: ${MYSQL_PWD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - database-volume:/var/lib/mysql
    depends_on:
      - app
    networks:
      - reactphp

# Docker Volumes
volumes:
  database-volume:

# Docker Networks
networks:
  reactphp:
